# Generated by Django 5.0.4 on 2024-05-01 17:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_details', models.TextField()),
                ('address', models.TextField()),
                ('vendor_code', models.CharField(blank=True, default=uuid.uuid4, max_length=120, unique=True)),
                ('on_time_delivery_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quality_rating_avg', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('average_response_time', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fulfillment_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Completed', 'completed'), ('Cancelled', 'Cancelled')], max_length=30)),
                ('quality_rating', models.FloatField(null=True)),
                ('issue_date', models.DateTimeField()),
                ('acknowledgment_date', models.DateTimeField(null=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vendor')),
            ],
        ),
    ]
