# Generated by Django 5.0.4 on 2024-05-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='owner',
        ),
    ]
