# Generated by Django 5.0.4 on 2024-05-02 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_vendor_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=120, unique=True),
        ),
    ]
